baseurl = "http://integerous.github.io/"
languageCode = "ko-kr"
title = "Integerous DevLog"
theme= "hugo-theme-geppaku"
googleAnalytics = "UA-126908369-1"
disqusShortname = ""

# pygmentsUseClassic ="true"
pygmentsStyle = "perldoc"
pygmentsCodeFences = "true"
# pygmentsCodeFencesGuessSyntax = "true"

hasCJKLanguage = "true"
paginate = "5"
newContentEditor = "Code"
enableEmoji = "true"
enableGitInfo = "true"
toc = "true"

[author]
    # If you want to display author information set these
    # This is Optional values
    name = "Jeongsu Han"

    # Please set account ids
    # This is Optional values
    twitter  = "integerous"
    linkedin = "integerous"
    github   = "integerous"
    instagram   = "ryemha_"

[params]
    custom_css = ["css/single.css"]

    [params.sharebutton]
        # If you want to display share buttons set these
        # This is Optional values
        twitter  = true
        facebook = true
        # tumblr   = true
        # hatena   = true # hatena is Japanese social media
        # google   = true
        # pocket   = true
        # Please set id when you want to display facebook
        # facebookAppId = "your app id"

    [params.adsense]
        # If you want to display Google adsense set these
        # This is Optional values
        # 1. Create file written of the adsense tag into the directory "layouts/partials"
        # 2. Please set file path name omitted "layouts/partials"
        sidebar = "adsense/sidebar.html"
        content = "adsense/content.html"

# [taxonomies]
#    tag = "tags"
#    category = "categories"
#    mood = "moods"